### ISSUE TITLE
Fix rendering of  GIFs

### ISSUE THREAD

**Issue by DanielRunningen** [I-question-this/DiscordPlaysPyBoy#6]
The timing between GIF frames is too high and makes the GIFs seem sluggish. Time should be decreased to their natural speed, maybe with a delay on the end of the GIF to signal where it ends (since it might not be clear in some cases, such as in menus).

**Comment by DanielRunningen** [comment]
Alternatively, the cursor seems to flicker in the dialog window. I'm unsure if this is a related issue.

**Comment by DanielRunningen** [comment]
Flowers (and people who turn in place) also seem to flash erratically.

**Comment by I-question-this** [comment]
It was thought that #27 resolved this issue (a bug was found in which the number of letters in the file path was used instead of the number of screenshots taken) but it wasn't a complete fix. Sometimes part of the GIF moves at a much slower or faster speed than the rest of the GIF.

It might be that the making of the GIFs is fine, and instead the emulation speed is causing problems. It is currently set to emulate as fast as possible, but it might be causing these issues. A new issue #31 has been created to investigate this. For the purposes of this issue I think it has been resolved.
